apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: rs-demo
    environment: dev
    tier: frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      purpose: rs-demo
      environment: dev
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        environment: dev
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.23-perl